name: Jay Nakum
email: contact.jaynakum@gmail.com

title: FOSMods
description: Free and Open Source Mods
baseurl: "/"
url: "https://fosmods.github.io"

theme: jekyll-theme-cayman
github:

is_project_page: true